// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/article/:articleSlug": {
    params: {
      "articleSlug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/article/:articleSlug";
  };
  "ui/pages/MainPage.tsx": {
    id: "ui/pages/MainPage";
    page: "/";
  };
  "ui/pages/ArticlePage.tsx": {
    id: "ui/pages/ArticlePage";
    page: "/article/:articleSlug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "ui/pages/MainPage": typeof import("./app/ui/pages/MainPage.tsx");
  "ui/pages/ArticlePage": typeof import("./app/ui/pages/ArticlePage.tsx");
};